### ISSUE TITLE
У мене не запускається скріпт.

### ISSUE THREAD

**Issue by RenmeiRei** [Z-beam/WinOpt#1]
![image](https://github.com/user-attachments/assets/671b7536-aa70-4646-9caa-810ec209fbf0)
Зробив все як зазначено в інструкції але не можу зрозуміти що пішло не так.

**Comment by Z-beam** [comment]
Швидше за все це через те, що ви використовуєте PowerShell (x86). Спробуйте зробити те ж саме, але через звичайний Windows PowerShell. Без x86 чи ISE. 
Також спробуйте оновити PowerShell за допомогою команди 
winget install --id Microsoft.Powershell --source winget

І обов'язково запускайте PowerShell від адміна.

**Comment by RenmeiRei** [comment]
Зробив. Те ж саме.
![image](https://github.com/user-attachments/assets/fa140fb2-99fa-456b-9d1f-1fa1506ab826)

**Comment by Z-beam** [comment]
Чи вносили ви якісь зміни до скрипту? Бо більшість помилок із вашого скриншоту - це помилки синтаксису. Типу зайві знаки, або недостатні знаки.
Це може бути через те, що браузер зламав синтаксис при збереженні. Спробуйте завантажити його знову вручну:
1. Клікніть на 11.ps1
![зображення](https://github.com/user-attachments/assets/089a2093-24d4-40bf-928d-b2fd69e67cf8)
2. Справа в кутку натисніть на стрілочку та завантажте скрипт файлом
![зображення](https://github.com/user-attachments/assets/e3735257-f8b1-4c64-8774-769314cd6fef)

Із синтаксисом в скрипті проблеми виключені, бо прямо зараз завантажив його з github та запустив на віртуальній машині. Все працює. Дайте знати, бо цікаво, що не так.

**Comment by RenmeiRei** [comment]
Ніяких змін не вносив. Все робив після відновлення системи.
![image](https://github.com/user-attachments/assets/1b8e27b2-1063-45d0-8759-5b6be25df286)

**Comment by Z-beam** [comment]
І якщо ви вводили winget install --id Microsoft.Powershell --source winget для оновлення powershell то можливо завантажився powershell 7 (x64) з чорним значком, а 5 залишився той самий, що був. На старішій 5 версії скрипт не працюватиме, на новіших 5 версіях - працює). Якщо є powershell 7 (x64), то з нього має працювати точно

**Comment by RenmeiRei** [comment]
![image](https://github.com/user-attachments/assets/8f2e2f50-6d37-4d19-8ca8-b3e662882561)
Запрацювало при завантаженні в ручну.

**Comment by Z-beam** [comment]
Ура! Підкажіть, через який браузер завантажували скрипт вперше? Щоб я протестував проблему

**Comment by RenmeiRei** [comment]
> Ура! Підкажіть, через який браузер завантажували скрипт вперше? Щоб я протестував проблему

Завантажував через Chrome Browser
