### ISSUE TITLE
Can't run the script without setting execution policy

### ISSUE THREAD

**Issue by kuguarpwnz** [Z-beam/WinOpt#7]
The changes introduced in https://github.com/Z-beam/WinOpt/pull/2 remove `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass` command from the readme file. Unfortunately, without this command PowerShell does not let me run the script. Here's the error message:

```
C:\Windows\system32> powershell -file "D:\11.ps1"
File D:\11.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Exe
cution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

![image](https://github.com/user-attachments/assets/62b2f56d-8241-4d25-9069-7753e07a415a)

**Comment by fixtrackers** [comment]
Ця помилка виникає через те, що на вашій системі відключено виконання скриптів PowerShell через політику безпеки. Щоб вирішити цю проблему, потрібно змінити політику виконання скриптів. Виконайте наступні кроки:
   Відкрийте PowerShell з правами адміністратора:
      Натисніть правою кнопкою миші на ярлик PowerShell і виберіть "Запустити від імені адміністратора".
      Введіть наступну команду, щоб дозволити виконання скриптів (встановити політику на RemoteSigned):

Set-ExecutionPolicy RemoteSigned

    Підтвердіть зміну політики, ввівши "Y" і натиснувши Enter.

    Спробуйте знову виконати ваш скрипт:

powershell -file "D:\11.ps1"
